### ISSUE TITLE
Truncate/Trim route length

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/bench-routes#279] opened 2020-07-20 06:00 UTC
<img width="1199" alt="Screenshot 2020-07-20 at 11 28 27 AM" src="https://user-images.githubusercontent.com/26324376/87904576-37d9d680-ca7c-11ea-8bd6-9b7c93387572.png">

The length of the route should be truncated to, say 40 characters to prevent them from overflowing over metrics.

**Comment by soulclimberchick** [comment] 2020-08-23 23:21
Hello, I would like to take a stab at this one. Can it be assigned to me?

**Comment by soulclimberchick** [comment] 2020-08-24 04:24
Hey there, I can't get this issue to reproduce. See screenshot. IT looks like it's being truncated by field width.
<img width="1552" alt="Screen Shot 2020-08-23 at 9 23 06 PM" src="https://user-images.githubusercontent.com/26016530/91003757-037b9d80-e587-11ea-8ff2-9d431b146252.png">

**Comment by aquibbaig** [comment] 2020-08-24 05:04
Hi, @soulclimberchick Thanks for the heads up. I think in most places this is handled by default by the table and in places where it is not we can make use of the `truncate` method defined in `dashboard/v1.1/src/utils/stringManipulations.ts`. In this specific case, if you'd use Firefox then the routes are no more truncated by default, for this inconsistent behaviour it seems wise enough to forcefully truncate these string values depending upon a constant factor, for example: to 50 character length. It would also make sense to add a tooltip on top of each string which would show the user the entire route `onMouseOver`, considering the fact if the user can't distinguish in between two routes which are almost identical but truncated, as follows:
```
www.reqres.in/my-api/v4.0/users/get-user?name="samuel"
www.reqres.in/my-api/v4.0/users/get-user?name="daniel"
```
will produce the same result `www.reqres.in/my-api/v4.0/users/` when truncated to say 32 characters.

**Comment by Harkishen-Singh** [comment] 2020-08-24 07:07
Not sure, but as far as I remember, this was done in the react UI with the extra long urls being shown in complete length when hovered over the text.

Also, @soulclimberchick if you want to contribute the react part, then install dependencies in `dashboard/v1.1` using `yarn install` (assuming you have yarn installed, else install yarn first. That's pretty simply. Let me know if you face any issues in that), and then in the root folder where the Makefile is present, `make view-v1.1` to start the react server. Then, go to localhost:3000 to use the UI.

**Comment by soulclimberchick** [comment] 2020-08-24 19:24
Thank you! I am a bit rusty in React but I've done several projects using it so I'm sure I can pick this up still. Those details are super handy to have in the issue tickets - especially for ones marked as good-first-issue since most of us picking those up are pretty green and flying blind in these open source projects. :) 

*Unrelated to this ticket* If either of you happen to know which open issues are in Go, I am trying to pick up more experience using Go but I am not very good at discerning which technology is being used with the descriptions in the open issues.

**Comment by Harkishen-Singh** [comment] 2020-08-24 19:32
@soulclimberchick its perfectly fine whether you are learning or gathering experience in any language. We will try our best to make comments that are sensible enough and solves the issues you are willing to solve.

In terms of the ease with Go and with this project, I will advise you to go through this. 

https://github.com/zairza-cetb/bench-routes/issues/165

This should involve both Go and a bit of React.

**Comment by soulclimberchick** [comment] 2020-08-24 19:36
You rock, thank you!

**Closed** 2021-03-13 11:59 UTC
Labels: bug, good first issue, ui-v1.1-enhancement
