### ISSUE TITLE
Remove redundancies in utils.BRMatrix

### ISSUE THREAD

**Issue by aquibbaig** [bench-routes/bench-routes#299] opened 2020-12-01 05:32 UTC
Inspecting the BRMatrix struct present in `types.go`, we find a lot of redundancies in the form of route's URI string used multiple times in a nested fashion, we instead could work on a more compact and precise data structure for the same. This can be solved as and when we migrate to a new TSDB.

**Comment by Tushar3099** [comment] 2021-03-17 18:05
I want to work on this issue @aquibbaig . Brief explaination of the possible approach for this issue will be helpfull. @Harkishen-Singh

**Comment by Harkishen-Singh** [comment] 2021-03-17 18:36
@Tushar3099 if you see the `types.go`, there are several structs that use repeated fields. The main aim here is to make them smaller and have a base struct which will be implemented in other structs and hence reducing redundancy.

Example: Ping and PingResp both have min, mean, max, mdev. So, PingResp can be rewritten as:

```golang
type PingResp struct {
        Ping
    	NormalizedTime int64   `json:"NormalizedTime"`
	Timestamp      string  `json:"Timestamp"`
	Relative       int     `json:"relative"`
}
```

But do make sure that base structs (which are being used to extend) have json implementations (like the current Ping does not have).

**Comment by Tushar3099** [comment] 2021-03-17 21:50
@Harkishen-Singh Thanks for the detailed explanation. I will try my best to refactor all the structs.

**Comment by Tushar3099** [comment] 2021-03-18 18:08
@Harkishen-Singh, I have solved the simpler redundancies like in `Ping` and `PingResp`, `FloodPing` and `FloodPingResp`, `Response` and `ResponseResp`.
But as @aquibbaig said the redundancy of routes URI in BRMatrix is nested, BRMatrix has a structure as : 
```
type BRMatrix struct {
	FullURL                  string
	Route                    parser.Route
	PingChain, JitterChain   *tsdb.Chain
	FPingChain, MonitorChain *tsdb.Chain
	Metrics                  *EndpointMetrics
}
```
Here `FullURL` has the route's URI, also the Route struct has the `URL` field : 
```
type Route struct {
	Method string    `yaml:"method"`
	URL    string    `yaml:"url"`
	Header []Headers `yaml:"headers"`
	Params []Params  `yaml:"params"`
	Body   []Body    `yaml:"body"`
	Labels []string  `yaml:"labels"`
}
```
and Chain struct also has a `Route` field 
```
type Chain struct {
	Path               string
	Name               string
	Route              string
	Chain              []Block
	LengthElements     int
	containsNewBlocks  bool
	inActiveIterations uint32
	mux                sync.Mutex
}
```
To remove this type of redundancy(if possible) the whole data structure has to be changed because all the redundant route data structs have their own implementation.
What should be the right approach?

**Comment by aquibbaig** [comment] 2021-03-19 05:28
@Tushar3099 Not sure if it is the right approach but if it trims down redundancies by any means, it will surely be helpful to the project. If entirely changing the type of the structs helps, please go ahead.

**Comment by Tushar3099** [comment] 2021-03-19 15:00
@aquibbaig @Harkishen-Singh, as I see, the structs Chain, Route, BRMatrix are widely used all over the code, and changing those data structs will then affect all the code and logic, and this will take some time. Shall I make a PR up to I have refactored other structs till then?

**Comment by Tushar3099** [comment] 2021-03-21 12:05
@Harkishen-Singh Please give your views on this: 

> @Harkishen-Singh, I have solved the simpler redundancies like in `Ping` and `PingResp`, `FloodPing` and `FloodPingResp`, `Response` and `ResponseResp`.
> But as @aquibbaig said the redundancy of routes URI in BRMatrix is nested, BRMatrix has a structure as :
> 
> ```
> type BRMatrix struct {
> 	FullURL                  string
> 	Route                    parser.Route
> 	PingChain, JitterChain   *tsdb.Chain
> 	FPingChain, MonitorChain *tsdb.Chain
> 	Metrics                  *EndpointMetrics
> }
> ```
> 
> Here `FullURL` has the route's URI, also the Route struct has the `URL` field :
> 
> ```
> type Route struct {
> 	Method string    `yaml:"method"`
> 	URL    string    `yaml:"url"`
> 	Header []Headers `yaml:"headers"`
> 	Params []Params  `yaml:"params"`
> 	Body   []Body    `yaml:"body"`
> 	Labels []string  `yaml:"labels"`
> }
> ```
> 
> and Chain struct also has a `Route` field
> 
> ```
> type Chain struct {
> 	Path               string
> 	Name               string
> 	Route              string
> 	Chain              []Block
> 	LengthElements     int
> 	containsNewBlocks  bool
> 	inActiveIterations uint32
> 	mux                sync.Mutex
> }
> ```
> 
> To remove this type of redundancy(if possible) the whole data structure has to be changed because all the redundant route data structs have their own implementation.
> What should be the right approach?

**Comment by Harkishen-Singh** [comment] 2021-03-21 12:08
Is the value on fullurl and route struct's url, the same?

**Comment by Tushar3099** [comment] 2021-03-21 12:15
@Harkishen-Singh, In this snippet from `main.go` line 141, we are assigning the route's URL to fullURL, so I assumed that routes `URL` field and BRMatrix `fullURL` field have the same value. Please correct me if I misunderstood.
```
	matrix[hash] = &utils.BRMatrix{
		FullURL:      r.URL,
		Route:        r,
		PingChain:    targetMachineCalc[uHash].Ping,
		JitterChain:  targetMachineCalc[uHash].Jitter,
		FPingChain:   targetMachineCalc[uHash].FPing,
		MonitorChain: tsdb.NewChain(pathMonitor).Init(),
		Metrics:      endpointMetrics,
	}
```

**Comment by Harkishen-Singh** [comment] 2021-03-21 12:23
Then that should be workable without the full url field. You can remove the full url field then and that should be good to go.

**Comment by Tushar3099** [comment] 2021-03-21 12:43
Thanks, I will then make the prescribed changes and make a PR ASAP.

**Comment by Tushar3099** [comment] 2021-03-27 12:04
@Harkishen-Singh @aquibbaig I think the issue is resolved so that we can close this issue.

**Closed** 2021-03-27 12:15 UTC
Labels: clean-up, not-easy
