### ISSUE TITLE
Tooltip required for minimized sidebar icons.

### ISSUE THREAD

**Issue by tasneemkoushar** [bench-routes/bench-routes#410] opened 2021-03-22 12:51 UTC
**Is your feature request related to a problem? Please describe.**
For new users, it would be a problem to analyze the working of the minimized sidebar icons, as even on hovering over the sidebar icons, no tooltip appears. As on the first visit to the website, new users might not get the intuition to click on a hamburger on the top left corner to get the icon's name. So it would be convenient for the users if we add some feature like a tooltip linked with the icons.

**Describe the solution you'd like**
Adding tooltips for minimized sidebar icons.

![issue with sidebar](https://user-images.githubusercontent.com/58592306/111991011-d782c380-8b39-11eb-997d-7a93462c9546.jpg)

**Additional Context**
I would like to work on this feature.

**Comment by tasneemkoushar** [comment] 2021-03-22 15:32
I want to work on it, please assign it to me.

**Comment by muskankhedia** [comment] 2021-03-22 16:17
@tasneemkoushar Welcome to the bench-routes project. I feel this is a duplicate of #352, regarding which the PR #360 has already been made.

**Comment by tasneemkoushar** [comment] 2021-03-22 18:42
Thank you @muskankhedia for paying attention to my issue. I didn't notice that the issue has already been raised. I will be looking forward to working as a part of bench routes by other issues.

**Closed** 2021-03-23 17:14 UTC
Labels: duplicate, feature
